;; Concatenate the BeefwifeCanvas runtime into dist/beefwife-canvas.js. One IIFE
;; keeps the runtime's file-level declarations out of page scope; the bundle's
;; only global is window.BeefwifeCanvas. Order matters: each file's load-time
;; dependency guards expect earlier files' declarations.
(require '[clojure.java.io :as io]
         '[clojure.string :as str])

(def files
  ["terrain/terrain.js"
   "beefwife/beefwife.js"
   "beefwife-canvas/beefwife-canvas-path.js"
   "beefwife-canvas/beefwife-canvas-steering.js"
   "beefwife-canvas/beefwife-canvas-actor.js"
   "beefwife-canvas/beefwife-canvas-options.js"
   "beefwife-canvas/beefwife-canvas-targeting.js"
   "beefwife-canvas/beefwife-canvas-population.js"
   "beefwife-canvas/beefwife-canvas-render.js"
   "beefwife-canvas/beefwife-canvas-scene.js"
   "beefwife-canvas/beefwife-canvas-runtime.js"
   "beefwife-canvas/beefwife-canvas-cast.js"
   "beefwife-canvas/beefwife-canvas-mount-options.js"
   "beefwife-canvas/beefwife-canvas.js"])

(def out "dist/beefwife-canvas.js")

(io/make-parents out)
(spit out
      (str "/* BeefwifeCanvas bundle. Generated by `bb bundle`; do not edit. */\n"
           "(() => {\n"
           (str/join "\n" (map slurp files))
           "\n})();\n"))
(println "wrote" out)
