const MAX_WORLD_COORDINATE = 1e9;
const MIN_PIXEL_RESOLUTION = 1e-6;
const MAX_PIXEL_RESOLUTION = 1e6;
const MAX_PERSPECTIVE = 1e6;

export {
  MAX_WORLD_COORDINATE,
  MIN_PIXEL_RESOLUTION,
  MAX_PIXEL_RESOLUTION,
  MAX_PERSPECTIVE,
};
